# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/OneDrive/VivadoProject/project_4/project_4.cache/wt [current_project]
set_property parent.project_path F:/OneDrive/VivadoProject/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/OneDrive/VivadoProject/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Adder.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Comparator.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Datapath_top.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/imports/new/Decoder_28_32.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/imports/new/Divider.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Fsm_controller.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Latch.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Memory.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Selector.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/imports/new/Show_Number.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/imports/new/pattern.v
  F:/OneDrive/VivadoProject/project_4/project_4.srcs/sources_1/new/Topest.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/OneDrive/VivadoProject/project_4/project_4.srcs/constrs_1/imports/VivadoProject/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/OneDrive/VivadoProject/project_4/project_4.srcs/constrs_1/imports/VivadoProject/Nexys4DDR_Master.xdc]


synth_design -top Topest -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Topest.dcp

catch { report_utilization -file Topest_utilization_synth.rpt -pb Topest_utilization_synth.pb }
