# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.cache/wt [current_project]
set_property parent.project_path C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/clock.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/display_time.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/light.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/main.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/man_walk.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/traffic.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/traffic_time.v
  C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/sources_1/imports/code/all.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/constrs_1/imports/code/Light.xdc
set_property used_in_implementation false [get_files C:/SoftWare/Vivado/Project/xinjie/TrafficLight/TrafficLight.srcs/constrs_1/imports/code/Light.xdc]


synth_design -top Main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
